linters:
  enable:
    - exportloopref
    - gocritic
    - gofmt
    - gofumpt
    - goimports
    - ifshort
    - makezero
    - nestif
    - revive
    - whitespace
    - nilnil
    - errname
    - errorlint
    - goerr113
    - ireturn
  disable:
    - deadcode
    - errcheck
    - structcheck
    - unused

issues:
  exclude-rules:
    - path: pkg/easyredir/client/types.go
      linters: errname
    - path: pkg/easyredir/client/client.go
      linters: ireturn

